# Generated by Django 3.0.3 on 2020-03-25 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrar_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('matricula', models.CharField(max_length=9, unique=True)),
                ('eliminado', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=1000)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateField(default=datetime.date.today)),
                ('nombre', models.CharField(max_length=150)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('eliminado', models.BooleanField(default=False)),
                ('asesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registrar_usuario.Usuario')),
                ('clasificacion', models.ManyToManyField(to='progeval.Clasificacion')),
                ('equipo', models.ManyToManyField(to='progeval.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('', '--Seleccione--'), ('Programada', 'Programada'), ('Cancelada', 'Cancelada'), ('Pospuesta', 'Pospuesta')], max_length=100)),
                ('eliminado', models.BooleanField(default=False)),
                ('jurado', models.ManyToManyField(to='registrar_usuario.Usuario')),
                ('presidenteJurado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presidente', to='registrar_usuario.Usuario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeval.Proyecto')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeval.Rubrica')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('peso', models.PositiveIntegerField()),
                ('eliminado', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='progeval.Item')),
                ('rubrica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progeval.Rubrica')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponderacion', models.PositiveIntegerField()),
                ('observaciones', models.TextField(max_length=1000)),
                ('eliminado', models.BooleanField(default=False)),
                ('programacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='progeval.Programacion')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeval.Rubrica')),
            ],
        ),
    ]
