# Generated by Django 3.0.3 on 2020-04-20 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrar_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=25)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=9, unique=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ciclo', models.CharField(max_length=50)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeval.Carrera')),
                ('numero_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeval.Clase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponderacion', models.PositiveIntegerField()),
                ('observaciones', models.TextField(max_length=1000)),
                ('hora', models.TimeField(default=datetime.datetime.now)),
                ('eliminado', models.BooleanField(default=False)),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar_usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=1000)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateField(default=datetime.date.today)),
                ('nombre', models.CharField(max_length=150)),
                ('valorIndicador', models.PositiveIntegerField(default=5)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('eliminado', models.BooleanField(default=False)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar_usuario.Usuario')),
                ('clasificacion', models.ManyToManyField(to='progeval.Clasificacion')),
                ('equipo', models.ManyToManyField(to='progeval.Estudiante')),
                ('numero_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeval.Clase')),
            ],
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField(default=datetime.datetime.now)),
                ('estado', models.CharField(choices=[('', '--Seleccione--'), ('Programada', 'Programada'), ('Cancelada', 'Cancelada'), ('Pospuesta', 'Pospuesta')], max_length=100)),
                ('ponderacion', models.PositiveIntegerField(blank=True, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('jurado', models.ManyToManyField(to='registrar_usuario.Usuario')),
                ('presidenteJurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidente', to='registrar_usuario.Usuario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeval.Proyecto')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeval.Rubrica')),
                ('rubrica_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rub_reporte', to='progeval.Rubrica')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorEvaluado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponderacion', models.PositiveIntegerField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeval.Evaluacion')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeval.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('peso', models.PositiveIntegerField()),
                ('eliminado', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='progeval.Item')),
                ('rubrica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progeval.Rubrica')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='programacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeval.Programacion'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeval.Rubrica'),
        ),
    ]
