# Generated by Django 3.0.3 on 2020-04-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='valorIndicador',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
