# Generated by Django 3.0.3 on 2020-04-04 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progeval', '0002_auto_20200327_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programacion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
