# Generated by Django 3.0.3 on 2020-04-04 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_usuario', '0001_initial'),
        ('progeval', '0003_auto_20200404_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='presidenteJurado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidente', to='registrar_usuario.Usuario'),
        ),
    ]
