# Generated by Django 3.0.3 on 2020-04-04 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progeval', '0004_auto_20200404_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='programacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeval.Programacion'),
        ),
    ]
